-- Run this once in Supabase: SQL Editor -> New query -> Run.
create table if not exists public.admin_users (
  email text primary key check (email = lower(email)),
  role text not null check (role in ('editor','admin','super_admin')),
  created_at timestamptz not null default now()
);
create table if not exists public.site_content (
  key text primary key,
  page text not null,
  value text not null,
  updated_by text not null,
  updated_at timestamptz not null default now()
);
create table if not exists public.news (
  id bigint generated by default as identity primary key,
  title text not null,
  category text not null default 'general' check (category in ('general', 'important', 'it', 'sport')),
  body text not null,
  author_email text not null,
  created_at timestamptz not null default now()
);
alter table public.admin_users enable row level security;
alter table public.site_content enable row level security;
alter table public.news enable row level security;

create or replace function public.is_site_admin() returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.admin_users where email = lower(coalesce(auth.jwt()->>'email','')) and role in ('admin','super_admin'))
$$;
revoke all on function public.is_site_admin() from public;
grant execute on function public.is_site_admin() to anon, authenticated;

create or replace function public.is_super_admin() returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.admin_users where email = lower(coalesce(auth.jwt()->>'email','')) and role = 'super_admin')
$$;
revoke all on function public.is_super_admin() from public;
grant execute on function public.is_super_admin() to anon, authenticated;

drop policy if exists "admins read own role" on public.admin_users;
create policy "admins read own role" on public.admin_users for select to authenticated using (email = lower(auth.jwt()->>'email'));
drop policy if exists "super admins manage users" on public.admin_users;
create policy "super admins manage users" on public.admin_users for all to authenticated using (public.is_super_admin()) with check (public.is_super_admin());
drop policy if exists "public reads content" on public.site_content;
create policy "public reads content" on public.site_content for select using (true);
drop policy if exists "admins edit content" on public.site_content;
create policy "admins edit content" on public.site_content for all to authenticated using (public.is_site_admin()) with check (public.is_site_admin());

drop policy if exists "public reads news" on public.news;
create policy "public reads news" on public.news for select using (true);
drop policy if exists "members publish news" on public.news;
create policy "members publish news" on public.news for insert to authenticated with check (
  exists (select 1 from public.admin_users where email = lower(auth.jwt()->>'email'))
  and author_email = lower(auth.jwt()->>'email')
);
drop policy if exists "admins manage news" on public.news;
create policy "admins manage news" on public.news for update to authenticated using (public.is_site_admin()) with check (public.is_site_admin());
drop policy if exists "super admins delete news" on public.news;
create policy "super admins delete news" on public.news for delete to authenticated using (public.is_super_admin());

insert into public.admin_users(email, role) values
 ('jopersimple@gmail.com','super_admin'),
 ('dov@vs.pl.ukr.education','admin')
on conflict (email) do update set role = excluded.role;

delete from public.admin_users where email = 'simplejoper@gmail.com';

-- CRITICAL: Grant table-level permissions to PostgreSQL roles
-- Without these, RLS policies alone won't allow any operations
GRANT ALL ON public.site_content TO authenticated;
GRANT ALL ON public.site_content TO anon;
GRANT SELECT ON public.site_content TO anon;

GRANT ALL ON public.admin_users TO authenticated;
GRANT SELECT ON public.admin_users TO anon;

GRANT ALL ON public.news TO authenticated;
GRANT SELECT ON public.news TO anon;

GRANT ALL ON public.comments TO authenticated;
GRANT SELECT ON public.comments TO anon;

-- TRUST MESSAGES TABLE
create table if not exists public.trust_messages (
  id bigint generated by default as identity primary key,
  name text not null default 'Анонімно',
  status text not null default 'other',
  subject text not null,
  message text not null,
  created_at timestamptz not null default now()
);

alter table public.trust_messages enable row level security;

drop policy if exists "public insert trust messages" on public.trust_messages;
create policy "public insert trust messages" on public.trust_messages for insert to anon, authenticated with check (true);

drop policy if exists "admins read trust messages" on public.trust_messages;
create policy "admins read trust messages" on public.trust_messages for select to authenticated using (public.is_site_admin());

GRANT ALL ON public.trust_messages TO authenticated;
GRANT ALL ON public.trust_messages TO anon;

-- SERVER-SIDE IP RATE-LIMITING TABLE & RPC FUNCTION FOR TRUST MESSAGES
create table if not exists public.trust_rate_limits (
  ip_address text primary key,
  last_submitted_at timestamptz not null default now()
);

alter table public.trust_rate_limits enable row level security;
grant select, insert, update on public.trust_rate_limits to anon, authenticated;

create or replace function public.submit_trust_message_secure(
  p_name text,
  p_status text,
  p_subject text,
  p_message text
) returns jsonb language plpgsql security definer set search_path = public as $$
declare
  v_headers jsonb;
  v_client_ip text;
  v_last_time timestamptz;
  v_cooldown_seconds int := 60;
begin
  -- Extract real client IP from Cloudflare/Supabase HTTP headers
  begin
    v_headers := current_setting('request.headers', true)::jsonb;
    v_client_ip := coalesce(
      v_headers->>'cf-connecting-ip',
      v_headers->>'x-forwarded-for',
      'unknown'
    );
    if v_client_ip like '%,%' then
      v_client_ip := split_part(v_client_ip, ',', 1);
    end if;
  exception when others then
    v_client_ip := 'unknown';
  end;

  -- Enforce server-side rate limit per IP
  if v_client_ip <> 'unknown' then
    select last_submitted_at into v_last_time
    from public.trust_rate_limits
    where ip_address = v_client_ip;

    if v_last_time is not null and (now() - v_last_time) < (v_cooldown_seconds || ' seconds')::interval then
      raise exception 'Зачекайте 1 хвилину перед наступною відправкою звернення (Серверне обмеження за IP)';
    end if;

    insert into public.trust_rate_limits(ip_address, last_submitted_at)
    values (v_client_ip, now())
    on conflict (ip_address) do update set last_submitted_at = now();
  end if;

  insert into public.trust_messages(name, status, subject, message)
  values (coalesce(nullif(trim(p_name), ''), 'Анонімно'), coalesce(p_status, 'other'), p_subject, p_message);

  return jsonb_build_object('success', true, 'message', 'Звернення надіслано');
end;
$$;

grant execute on function public.submit_trust_message_secure(text, text, text, text) to anon, authenticated;

-- Also grant usage on sequences if any
GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO authenticated;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO anon;
