-- Run this once in Supabase: SQL Editor -> New query -> Run.
create table if not exists public.admin_users (
  email text primary key check (email = lower(email)),
  role text not null check (role in ('editor','admin','super_admin')),
  created_at timestamptz not null default now()
);
create table if not exists public.site_content (
  key text primary key,
  page text not null,
  value text not null,
  updated_by text not null,
  updated_at timestamptz not null default now()
);
create table if not exists public.news (
  id bigint generated by default as identity primary key,
  title text not null,
  category text not null default 'general' check (category in ('general', 'important', 'it', 'sport')),
  body text not null,
  author_email text not null,
  created_at timestamptz not null default now()
);
alter table public.admin_users enable row level security;
alter table public.site_content enable row level security;
alter table public.news enable row level security;

create or replace function public.is_site_admin() returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.admin_users where email = lower(coalesce(auth.jwt()->>'email','')) and role in ('admin','super_admin'))
$$;
revoke all on function public.is_site_admin() from public;
grant execute on function public.is_site_admin() to anon, authenticated;

create or replace function public.is_super_admin() returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.admin_users where email = lower(coalesce(auth.jwt()->>'email','')) and role = 'super_admin')
$$;
revoke all on function public.is_super_admin() from public;
grant execute on function public.is_super_admin() to anon, authenticated;

drop policy if exists "admins read own role" on public.admin_users;
create policy "admins read own role" on public.admin_users for select to authenticated using (email = lower(auth.jwt()->>'email'));
drop policy if exists "super admins manage users" on public.admin_users;
create policy "super admins manage users" on public.admin_users for all to authenticated using (public.is_super_admin()) with check (public.is_super_admin());
drop policy if exists "public reads content" on public.site_content;
create policy "public reads content" on public.site_content for select using (true);
drop policy if exists "admins edit content" on public.site_content;
create policy "admins edit content" on public.site_content for all to authenticated using (public.is_site_admin()) with check (public.is_site_admin());

drop policy if exists "public reads news" on public.news;
create policy "public reads news" on public.news for select using (true);
drop policy if exists "members publish news" on public.news;
create policy "members publish news" on public.news for insert to authenticated with check (
  exists (select 1 from public.admin_users where email = lower(auth.jwt()->>'email'))
  and author_email = lower(auth.jwt()->>'email')
);
drop policy if exists "admins manage news" on public.news;
create policy "admins manage news" on public.news for update to authenticated using (public.is_site_admin()) with check (public.is_site_admin());
drop policy if exists "super admins delete news" on public.news;
create policy "super admins delete news" on public.news for delete to authenticated using (public.is_super_admin());

insert into public.admin_users(email, role) values
 ('jopersimple@gmail.com','super_admin'),
 ('dov@vs.pl.ukr.education','admin')
on conflict (email) do update set role = excluded.role;

delete from public.admin_users where email = 'simplejoper@gmail.com';

-- CRITICAL: Grant table-level permissions to PostgreSQL roles
-- Without these, RLS policies alone won't allow any operations
GRANT ALL ON public.site_content TO authenticated;
GRANT ALL ON public.site_content TO anon;
GRANT SELECT ON public.site_content TO anon;

GRANT ALL ON public.admin_users TO authenticated;
GRANT SELECT ON public.admin_users TO anon;

GRANT ALL ON public.news TO authenticated;
GRANT SELECT ON public.news TO anon;

GRANT ALL ON public.comments TO authenticated;
GRANT SELECT ON public.comments TO anon;

-- Also grant usage on sequences if any
GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO authenticated;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO anon;
