-- =========================================================================
-- VELYKOSOROCHYNTSI LYCEUM - SECURE SUPABASE DATABASE SCHEMA & RLS SETUP
-- =========================================================================
-- Instructions: Paste this in Supabase SQL Editor, replace YOUR_TURNSTILE_SECRET_KEY
-- with your actual Cloudflare secret key, and click Run.

create extension if not exists http with schema extensions;

-- 1. ADMIN USERS TABLE
create table if not exists public.admin_users (
  email text primary key check (email = lower(email)),
  role text not null check (role in ('editor','admin','super_admin')),
  created_at timestamptz not null default now()
);
alter table public.admin_users enable row level security;

-- 2. SITE CONTENT (Editable text)
create table if not exists public.site_content (
  key text primary key,
  page text not null,
  value text not null,
  updated_by text not null,
  updated_at timestamptz not null default now()
);
alter table public.site_content enable row level security;

-- 3. NEWS TABLE
create table if not exists public.news (
  id bigint generated by default as identity primary key,
  title text not null,
  category text not null default 'general' check (category in ('general', 'important', 'it', 'sport')),
  body text not null,
  author_email text not null,
  created_at timestamptz not null default now()
);
alter table public.news enable row level security;

-- 4. DOCUMENTS TABLE (with Server-side URL Scheme Validation)
create table if not exists public.documents (
  id bigint generated by default as identity primary key,
  title text not null,
  type text not null default 'normative',
  url text not null,
  author_email text not null,
  created_at timestamptz not null default now()
);
alter table public.documents enable row level security;

alter table public.documents add column if not exists url text;
alter table public.documents drop constraint if exists documents_url_check;
alter table public.documents add constraint documents_url_check check (url is null or url ~* '^https?://[^\s<>"]+$');

-- 5. SCHEDULE TABLE
create table if not exists public.schedule (
  class text primary key,
  lessons jsonb not null default '{}'::jsonb,
  updated_by text not null,
  updated_at timestamptz not null default now()
);
alter table public.schedule enable row level security;

-- 6. TRUST MESSAGES (Скринька довіри)
create table if not exists public.trust_messages (
  id bigint generated by default as identity primary key,
  name text not null default 'Анонімно',
  status text not null default 'other',
  subject text not null,
  message text not null,
  created_at timestamptz not null default now()
);
alter table public.trust_messages enable row level security;

-- 7. COMMENTS & REVIEWS TABLE
create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  page text not null default '/index.html',
  author_name text not null default 'Гість',
  author_email text,
  content text not null,
  created_at timestamptz not null default now()
);
alter table public.comments enable row level security;

-- 8. RATE LIMIT TABLES (Strictly Private)
create table if not exists public.trust_rate_limits (
  ip_address text primary key,
  last_submitted_at timestamptz not null default now()
);
alter table public.trust_rate_limits enable row level security;

create table if not exists public.comment_rate_limits (
  ip_address text primary key,
  last_submitted_at timestamptz not null default now()
);
alter table public.comment_rate_limits enable row level security;

create table if not exists public.comment_user_rate_limits (
  user_id uuid primary key,
  last_submitted_at timestamptz not null default now()
);
alter table public.comment_user_rate_limits enable row level security;


-- =========================================================================
-- SECURITY FUNCTIONS & RLS POLICIES
-- =========================================================================

-- Helper functions
create or replace function public.is_site_admin() returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.admin_users where email = lower(coalesce(auth.jwt()->>'email','')) and role in ('admin','super_admin'))
$$;
revoke all on function public.is_site_admin() from public;
grant execute on function public.is_site_admin() to anon, authenticated;

create or replace function public.is_super_admin() returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.admin_users where email = lower(coalesce(auth.jwt()->>'email','')) and role = 'super_admin')
$$;
revoke all on function public.is_super_admin() from public;
grant execute on function public.is_super_admin() to anon, authenticated;

-- Deduplicate Production Policies & Re-apply Clean RLS Policies

-- Policies: admin_users
drop policy if exists "admins read own role" on public.admin_users;
drop policy if exists "admin_users_select_own" on public.admin_users;
create policy "admins read own role" on public.admin_users for select to authenticated using (email = lower(auth.jwt()->>'email'));

drop policy if exists "super admins manage users" on public.admin_users;
drop policy if exists "super_admin_manage_users" on public.admin_users;
create policy "super admins manage users" on public.admin_users for all to authenticated using (public.is_super_admin()) with check (public.is_super_admin());

-- Policies: site_content
drop policy if exists "public reads content" on public.site_content;
drop policy if exists "site_content_public_read" on public.site_content;
create policy "public reads content" on public.site_content for select using (true);

drop policy if exists "admins edit content" on public.site_content;
drop policy if exists "site_content_admins_edit" on public.site_content;
create policy "admins edit content" on public.site_content for all to authenticated using (public.is_site_admin()) with check (public.is_site_admin());

-- Policies: news
drop policy if exists "public reads news" on public.news;
drop policy if exists "news_public_read" on public.news;
create policy "public reads news" on public.news for select using (true);

drop policy if exists "members publish news" on public.news;
create policy "members publish news" on public.news for insert to authenticated with check (
  exists (select 1 from public.admin_users where email = lower(auth.jwt()->>'email'))
  and author_email = lower(auth.jwt()->>'email')
);

drop policy if exists "admins manage news" on public.news;
create policy "admins manage news" on public.news for update to authenticated using (public.is_site_admin()) with check (public.is_site_admin());

drop policy if exists "super admins delete news" on public.news;
create policy "super admins delete news" on public.news for delete to authenticated using (public.is_super_admin());

-- Policies: documents (Deduplicate)
drop policy if exists "public reads documents" on public.documents;
drop policy if exists "documents_public_read" on public.documents;
create policy "public reads documents" on public.documents for select using (true);

drop policy if exists "admins manage documents" on public.documents;
drop policy if exists "admins_manage_documents" on public.documents;
drop policy if exists "documents_admins_all" on public.documents;
create policy "admins manage documents" on public.documents for all to authenticated using (public.is_site_admin()) with check (public.is_site_admin());

-- Policies: schedule
drop policy if exists "public reads schedule" on public.schedule;
drop policy if exists "schedule_public_read" on public.schedule;
create policy "public reads schedule" on public.schedule for select using (true);

drop policy if exists "admins manage schedule" on public.schedule;
drop policy if exists "schedule_admins_all" on public.schedule;
create policy "admins manage schedule" on public.schedule for all to authenticated using (public.is_site_admin()) with check (public.is_site_admin());

-- Policies: trust_messages (Deduplicate)
drop policy if exists "admins read trust messages" on public.trust_messages;
drop policy if exists "trust_messages_admins_select" on public.trust_messages;
create policy "admins read trust messages" on public.trust_messages for select to authenticated using (public.is_site_admin());

drop policy if exists "admins delete trust messages" on public.trust_messages;
drop policy if exists "trust_messages_admins_delete" on public.trust_messages;
create policy "admins delete trust messages" on public.trust_messages for delete to authenticated using (public.is_site_admin());

-- Policies: comments (Deduplicate)
drop policy if exists "public read comments" on public.comments;
drop policy if exists "comments_public_read" on public.comments;
drop policy if exists "public reads comments" on public.comments;
create policy "public read comments" on public.comments for select using (true);

drop policy if exists "admins delete comments" on public.comments;
drop policy if exists "comments_admins_delete" on public.comments;
drop policy if exists "comments_author_delete" on public.comments;
drop policy if exists "authors and admins delete comments" on public.comments;
create policy "authors and admins delete comments" on public.comments for delete to authenticated
using (
  public.is_site_admin()
  or author_email = lower(coalesce(auth.jwt()->>'email', ''))
);

drop policy if exists "comments_author_update" on public.comments;
drop policy if exists "authors update own comments" on public.comments;

-- Initial Super Admins
insert into public.admin_users(email, role) values
 ('jopersimple@gmail.com','super_admin'),
 ('dov@vs.pl.ukr.education','admin')
on conflict (email) do update set role = excluded.role;

-- =========================================================================
-- STRICT GRANT / REVOKE (Deny by Default + Least Privilege)
-- =========================================================================

-- Revoke all public/anon/authenticated grants from rate limit tables
revoke all on public.trust_rate_limits from public, anon, authenticated;
revoke all on public.comment_rate_limits from public, anon, authenticated;
revoke all on public.comment_user_rate_limits from public, anon, authenticated;

-- admin_users: anon gets NOTHING; authenticated gets SELECT, INSERT, UPDATE, DELETE (RLS controls row access)
revoke all on public.admin_users from public, anon;
grant select, insert, update, delete on public.admin_users to authenticated;
revoke references, trigger on public.admin_users from public, anon, authenticated;

-- site_content: anon & authenticated get SELECT; write operations restricted to authenticated
revoke insert, update, delete on public.site_content from public, anon;
grant select on public.site_content to anon, authenticated;
grant insert, update on public.site_content to authenticated;

-- news: anon gets SELECT; authenticated gets SELECT, INSERT, UPDATE, DELETE (RLS controls who actually can)
revoke insert, update, delete on public.news from public, anon;
grant select on public.news to anon, authenticated;
grant insert, update, delete on public.news to authenticated;

-- documents: anon gets SELECT; authenticated gets SELECT, INSERT, UPDATE, DELETE (RLS controls who actually can)
revoke insert, update, delete on public.documents from public, anon;
grant select on public.documents to anon, authenticated;
grant insert, update, delete on public.documents to authenticated;

-- schedule: anon gets SELECT; authenticated gets SELECT, INSERT, UPDATE (RLS controls who actually can)
revoke insert, update, delete on public.schedule from public, anon;
grant select on public.schedule to anon, authenticated;
grant insert, update on public.schedule to authenticated;

-- comments: anon & authenticated get SELECT; direct INSERT revoked (must use RPC); DELETE allowed for authenticated (RLS enforced)
revoke insert, update on public.comments from public, anon, authenticated;
grant select on public.comments to anon, authenticated;
grant delete on public.comments to authenticated;

-- trust_messages: anon gets NOTHING; authenticated gets SELECT, DELETE (RLS limits to admins)
revoke all on public.trust_messages from public, anon;
grant select, delete on public.trust_messages to authenticated;



-- Explicitly REVOKE TRUNCATE for client roles (public, anon, authenticated) across all security-sensitive tables
revoke truncate on public.admin_users from public, anon, authenticated;
revoke truncate on public.comments from public, anon, authenticated;
revoke truncate on public.news from public, anon, authenticated;
revoke truncate on public.documents from public, anon, authenticated;
revoke truncate on public.site_content from public, anon, authenticated;
revoke truncate on public.schedule from public, anon, authenticated;
revoke truncate on public.trust_messages from public, anon, authenticated;
revoke truncate on public.trust_rate_limits from public, anon, authenticated;
revoke truncate on public.comment_rate_limits from public, anon, authenticated;
revoke truncate on public.comment_user_rate_limits from public, anon, authenticated;


-- =========================================================================
-- SECURE RPC: SUBMIT TRUST MESSAGE (Strict Fail-Closed, IP Protected)
-- =========================================================================
drop function if exists public.submit_trust_message_secure(text, text, text, text);
drop function if exists public.submit_trust_message_secure(text, text, text, text, text);

create or replace function public.submit_trust_message_secure(
  p_name text,
  p_status text,
  p_subject text,
  p_message text,
  p_turnstile_token text default null
) returns jsonb language plpgsql security definer set search_path = public as $$
declare
  v_headers jsonb;
  v_client_ip text;
  v_cooldown_seconds int := 60;
  -- Set your real secret key here directly in Supabase SQL editor (never commit real secret to git)
  v_turnstile_secret text := 'YOUR_TURNSTILE_SECRET_KEY';
  v_turnstile_ok boolean := false;
  v_http_response extensions.http_response;
  v_response_body jsonb;
begin
  -- 1. Server-side string length validations
  if p_message is null or trim(p_message) = '' then
    raise exception 'Текст звернення не може бути порожнім';
  end if;
  if length(p_message) > 5000 then
    raise exception 'Текст звернення занадто довгий (максимум 5000 символів)';
  end if;
  if p_subject is null or trim(p_subject) = '' then
    raise exception 'Тема звернення не може бути порожньою';
  end if;
  if length(p_subject) > 200 then
    raise exception 'Тема звернення занадто довга (максимум 200 символів)';
  end if;
  if p_name is not null and length(p_name) > 100 then
    raise exception 'Ім''я занадто довге (максимум 100 символів)';
  end if;
  -- Validate p_status against whitelist
  if p_status is not null and p_status not in ('student', 'parent', 'teacher', 'other', '') then
    raise exception 'Невідомий статус';
  end if;

  -- 2. Turnstile Captcha verification (Strict Fail-Closed)
  if p_turnstile_token is null or trim(p_turnstile_token) = '' then
    raise exception 'Пройдіть перевірку безпеки (капчу)';
  end if;

  if v_turnstile_secret is null or v_turnstile_secret = '' or v_turnstile_secret = 'YOUR_TURNSTILE_SECRET_KEY' then
    raise exception 'Секретний ключ капчі не налаштований на сервері';
  end if;

  begin
    select * into v_http_response from extensions.http_post(
      'https://challenges.cloudflare.com/turnstile/v0/siteverify',
      json_build_object(
        'secret', v_turnstile_secret,
        'response', trim(p_turnstile_token)
      )::text,
      'application/json'
    );
    v_response_body := v_http_response.content::jsonb;
    v_turnstile_ok := coalesce((v_response_body->>'success')::boolean, false);
  exception when others then
    raise exception 'Помилка з''єднання з сервісом перевірки безпеки. Спробуйте пізніше.';
  end;

  if not v_turnstile_ok then
    raise exception 'Перевірка безпеки не пройдена. Оновіть сторінку.';
  end if;

  -- 3. Extract real client IP
  begin
    v_headers := current_setting('request.headers', true)::jsonb;
    v_client_ip := coalesce(
      nullif(trim(v_headers->>'cf-connecting-ip'), ''),
      'unknown'
    );
    if v_client_ip like '%,%' then
      v_client_ip := split_part(v_client_ip, ',', 1);
    end if;
  exception when others then
    v_client_ip := 'unknown';
  end;

  -- 4. Atomic Rate Limit (Race Condition Proof & Fail-Closed)
  insert into public.trust_rate_limits(ip_address, last_submitted_at)
  values (v_client_ip, now())
  on conflict (ip_address) do update
  set last_submitted_at = now()
  where public.trust_rate_limits.last_submitted_at <= (now() - (v_cooldown_seconds || ' seconds')::interval);

  if not found then
    raise exception 'Зачекайте 1 хвилину перед наступною відправкою звернення';
  end if;

  -- 5. Insert trust message
  insert into public.trust_messages(name, status, subject, message)
  values (
    coalesce(nullif(trim(p_name), ''), 'Анонімно'),
    coalesce(nullif(trim(p_status), ''), 'other'),
    trim(p_subject),
    trim(p_message)
  );

  return jsonb_build_object('success', true, 'message', 'Звернення надіслано');
end;
$$;

revoke all on function public.submit_trust_message_secure(text, text, text, text, text) from public;
grant execute on function public.submit_trust_message_secure(text, text, text, text, text) to anon, authenticated;


-- =========================================================================
-- SECURE RPC: SUBMIT COMMENT (Authenticated-Only, Dual Rate Limit, Fail-Closed)
-- =========================================================================
drop function if exists public.submit_comment_secure(text, text, text, text);

create or replace function public.submit_comment_secure(
  p_page text,
  p_author_name text,
  p_content text,
  p_turnstile_token text default null
) returns jsonb language plpgsql security definer set search_path = public as $$
declare
  v_headers jsonb;
  v_client_ip text;
  v_cooldown_seconds int := 20;
  -- Set your real secret key here directly in Supabase SQL editor (never commit real secret to git)
  v_turnstile_secret text := 'YOUR_TURNSTILE_SECRET_KEY';
  v_turnstile_ok boolean := false;
  v_http_response extensions.http_response;
  v_response_body jsonb;
  v_auth_user_id uuid;
  v_auth_email text;
  v_auth_name text;
begin
  -- 1. Server-side authentication check (STRICT: no anonymous comments)
  v_auth_user_id := auth.uid();
  if v_auth_user_id is null then
    raise exception 'Authentication required';
  end if;

  v_auth_email := lower(coalesce(auth.jwt()->>'email', ''));
  if v_auth_email = '' then
    raise exception 'Недійсний акаунт (відсутній email)';
  end if;

  v_auth_name := coalesce(
    nullif(trim(auth.jwt()->>'name'), ''),
    nullif(trim(auth.jwt()->'user_metadata'->>'full_name'), ''),
    nullif(trim(auth.jwt()->'user_metadata'->>'name'), ''),
    nullif(trim(p_author_name), ''),
    'Користувач'
  );
  if length(v_auth_name) > 100 then
    v_auth_name := substring(v_auth_name from 1 for 100);
  end if;

  -- 2. Length & content checks
  if p_content is null or trim(p_content) = '' then
    raise exception 'Текст відгуку не може бути порожнім';
  end if;
  if length(p_content) > 3000 then
    raise exception 'Текст відгуку занадто довгий (максимум 3000 символів)';
  end if;
  if p_page is not null and length(p_page) > 200 then
    raise exception 'Невалідна сторінка';
  end if;

  -- 3. Turnstile Captcha verification (Strict Fail-Closed)
  if p_turnstile_token is null or trim(p_turnstile_token) = '' then
    raise exception 'Пройдіть перевірку безпеки (капчу)';
  end if;

  if v_turnstile_secret is null or v_turnstile_secret = '' or v_turnstile_secret = 'YOUR_TURNSTILE_SECRET_KEY' then
    raise exception 'Секретний ключ капчі не налаштований на сервері';
  end if;

  begin
    select * into v_http_response from extensions.http_post(
      'https://challenges.cloudflare.com/turnstile/v0/siteverify',
      json_build_object(
        'secret', v_turnstile_secret,
        'response', trim(p_turnstile_token)
      )::text,
      'application/json'
    );
    v_response_body := v_http_response.content::jsonb;
    v_turnstile_ok := coalesce((v_response_body->>'success')::boolean, false);
  exception when others then
    raise exception 'Помилка з''єднання з сервісом перевірки безпеки. Спробуйте пізніше.';
  end;

  if not v_turnstile_ok then
    raise exception 'Перевірка безпеки не пройдена. Оновіть сторінку.';
  end if;

  -- 4. User-based Rate Limit
  insert into public.comment_user_rate_limits(user_id, last_submitted_at)
  values (v_auth_user_id, now())
  on conflict (user_id) do update
  set last_submitted_at = now()
  where public.comment_user_rate_limits.last_submitted_at <= (now() - (v_cooldown_seconds || ' seconds')::interval);

  if not found then
    raise exception 'Зачекайте 20 секунд перед додаванням наступного відгуку';
  end if;

  -- 5. IP-based Rate Limit
  begin
    v_headers := current_setting('request.headers', true)::jsonb;
    v_client_ip := coalesce(
      nullif(trim(v_headers->>'cf-connecting-ip'), ''),
      'unknown'
    );
    if v_client_ip like '%,%' then
      v_client_ip := split_part(v_client_ip, ',', 1);
    end if;
  exception when others then
    v_client_ip := 'unknown';
  end;

  insert into public.comment_rate_limits(ip_address, last_submitted_at)
  values (v_client_ip, now())
  on conflict (ip_address) do update
  set last_submitted_at = now()
  where public.comment_rate_limits.last_submitted_at <= (now() - (v_cooldown_seconds || ' seconds')::interval);

  if not found then
    raise exception 'Зачекайте 20 секунд перед додаванням наступного відгуку';
  end if;

  -- 6. Insert comment
  insert into public.comments(page, author_name, author_email, content)
  values (
    coalesce(nullif(trim(p_page), ''), '/index.html'),
    v_auth_name,
    v_auth_email,
    trim(p_content)
  );

  return jsonb_build_object('success', true, 'message', 'Відгук опубліковано');
end;
$$;

revoke all on function public.submit_comment_secure(text, text, text, text) from public, anon;
grant execute on function public.submit_comment_secure(text, text, text, text) to authenticated;
